### ISSUE TITLE
Removing Melonloader folder

### ISSUE THREAD

**Issue by CaimCaerleon** [Slaynash/MelonWiki#27]
The Mono-2.0-bdwgc.dll inside the Melonloader folder refuses to allow me to delete it, saying some other program is using it.  Nothing else is open, tried using Process Handler to stop it there, and no dice.  Couldn't install new version of Melonloader since that folder can't be removed due to dll inside.   Was able to rename the folder and then run MelonLoader installer, and it installed successfully, EMM working find in desktop mode.  Folder and that mono-2.0-bdwgc.dll still exist, unremovable.

**Comment by loukylor** [comment]
Try restarting your computer, or try moving the melonloader folder and deleting it after moving it.
